export default {
  id: "forge-api",
  priority: 118,
  alias: "forge",
  aliases: [
    "fa",
    "forge-api",
  ],
  uiAlias: "forge",
  display: {
    name: "Forge API",
    icon: "bolt",
    color: "#F59E0B",
    textIcon: "FA",
    website: "https://forge-ai.space",
    notice: {
      text: "OpenAI-compatible multi-model gateway. API key auth.",
      apiKeyUrl: "https://forge-ai.space/",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://forge-gateway-api.fly.dev/v1/chat/completions",
    validateUrl: "https://forge-gateway-api.fly.dev/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "claude-opus-4-5-20251101", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4.5" },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5" },
    { id: "grok-4.5", name: "Grok 4.5" },
    { id: "grok-4.3", name: "Grok 4.3" },
    { id: "grok-build-0.1", name: "Grok Build 0.1" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-4-6-thinking", name: "Claude Sonnet 4.6 Thinking" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "deepseek-v3.1", name: "DeepSeek V3.1" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "deepseek-v3", name: "DeepSeek V3" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "gemini-3-pro-preview", name: "Gemini 3 Pro Preview" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "tencent/hy3", name: "Tencent Hunyuan 3" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "MiniMax-M3", name: "MiniMax M3" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "glm-5.2", name: "GLM-5.2" },
  ],
  modelsFetcher: { url: "https://forge-gateway-api.fly.dev/v1/models", type: "openai" },
  passthroughModels: true,
};
