export default {
  id: "inferhub",
  priority: 116,
  alias: "inferhub",
  aliases: [
    "ih",
  ],
  uiAlias: "inferhub",
  display: {
    name: "InferHub",
    icon: "hub",
    color: "#6366F1",
    textIcon: "IH",
    website: "https://inferhub.dev",
    notice: {
      text: "OpenAI-compatible multi-provider hub. Models use prefixed ids (cb/, cc/, cmc/, …) plus short aliases.",
      apiKeyUrl: "https://inferhub.dev/dashboard/keys",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.inferhub.dev/v1/chat/completions",
    validateUrl: "https://api.inferhub.dev/v1/models",
    thinkingFormat: "openai",
  },
  // Curated seed (aliases + popular prefixed models); full catalogue via modelsFetcher.
  models: [
    { id: "claude-opus-4.7", name: "Claude Opus 4.7 (alias)" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6 (alias)" },
    { id: "gpt-5.5", name: "GPT-5.5 (alias)" },
    { id: "gpt-5.4", name: "GPT-5.4 (alias)" },
    { id: "glm-5.2", name: "GLM-5.2 (alias)" },
    { id: "glm-5.1", name: "GLM-5.1 (alias)" },
    { id: "glm-5", name: "GLM-5 (alias)" },
    { id: "kimi-k2.6", name: "Kimi K2.6 (alias)" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code (alias)" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro (alias)" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash (alias)" },
    { id: "minimax-m3", name: "MiniMax M3 (alias)" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro (alias)" },
    { id: "mimo-v2.5", name: "MiMo V2.5 (alias)" },
    { id: "longcat-2.0", name: "LongCat 2.0 (alias)" },
    { id: "cc/claude-sonnet-4-6", name: "Claude Sonnet 4.6 (CC)" },
    { id: "cc/claude-opus-4-7", name: "Claude Opus 4.7 (CC)" },
    { id: "cb/claude-opus-4.6", name: "Claude Opus 4.6 (CB)" },
    { id: "cb/gpt-5.5", name: "GPT-5.5 (CB)" },
    { id: "cx/gpt-5.5", name: "GPT-5.5 (CX)" },
    { id: "zai/glm-5.2", name: "GLM-5.2 (ZAI)" },
    { id: "cmc/deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro (CMC)" },
    { id: "sf/moonshotai/Kimi-K2.6", name: "Kimi K2.6 (SF)" },
    { id: "ocg/minimax-m3", name: "MiniMax M3 (OCG)" },
  ],
  serviceKinds: ["llm"],
  modelsFetcher: { url: "https://api.inferhub.dev/v1/models", type: "openai" },
  passthroughModels: true,
};
