export default {
  id: "inferhub",
  priority: 116,
  alias: "inferhub",
  aliases: [
    "ih",
  ],
  uiAlias: "inferhub",
  display: {
    name: "InferHub",
    icon: "hub",
    color: "#6366F1",
    textIcon: "IH",
    website: "https://inferhub.dev",
    notice: {
      text: "OpenAI-compatible multi-provider hub. Models use prefixed ids (cb/, cc/, cmc/, …) plus short aliases.",
      apiKeyUrl: "https://inferhub.dev/dashboard/keys",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.inferhub.dev/v1/chat/completions",
    validateUrl: "https://api.inferhub.dev/v1/models",
    thinkingFormat: "openai",
  },
  // Full catalogue snapshot from InferHub's /v1/models (owned_by ids are real
  // model ids, not display aliases — refresh via modelsFetcher when it drifts).
  models: [
    { id: "cb/claude-opus-4.6", name: "Claude Opus 4.6 (CB)" },
    { id: "cb/claude-opus-4.7-1m", name: "Claude Opus 4.7 1M (CB)" },
    { id: "cb/gemini-3.1-pro", name: "Gemini 3.1 Pro (CB)" },
    { id: "cb/gpt-5.3-codex", name: "GPT-5.3 Codex (CB)" },
    { id: "cb/gpt-5.4", name: "GPT-5.4 (CB)" },
    { id: "cb/gpt-5.5", name: "GPT-5.5 (CB)" },
    { id: "cb/kimi-k2.5", name: "Kimi K2.5 (CB)" },
    { id: "cc/claude-haiku-4-5", name: "Claude Haiku 4.5 (CC)" },
    { id: "cc/claude-opus-4-6", name: "Claude Opus 4.6 (CC)" },
    { id: "cc/claude-opus-4-7", name: "Claude Opus 4.7 (CC)" },
    { id: "cc/claude-opus-4-8", name: "Claude Opus 4.8 (CC)" },
    { id: "cc/claude-sonnet-4-5", name: "Claude Sonnet 4.5 (CC)" },
    { id: "cc/claude-sonnet-4-6", name: "Claude Sonnet 4.6 (CC)" },
    { id: "cc/claude-sonnet-5", name: "Claude Sonnet 5 (CC)" },
    { id: "cmc/MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5 (CMC)" },
    { id: "cmc/MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7 (CMC)" },
    { id: "cmc/Qwen/Qwen3.6-Max-Preview", name: "Qwen3.6 Max Preview (CMC)" },
    { id: "cmc/Qwen/Qwen3.6-Plus", name: "Qwen3.6 Plus (CMC)" },
    { id: "cmc/deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash (CMC)" },
    { id: "cmc/deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro (CMC)" },
    { id: "cmc/moonshotai/Kimi-K2.5", name: "Kimi K2.5 (CMC)" },
    { id: "cmc/moonshotai/Kimi-K2.6", name: "Kimi K2.6 (CMC)" },
    { id: "cmc/stepfun/Step-3.5-Flash", name: "Step 3.5 Flash (CMC)" },
    { id: "cmc/zai-org/GLM-5", name: "GLM-5 (CMC)" },
    { id: "cmc/zai-org/GLM-5.1", name: "GLM-5.1 (CMC)" },
    { id: "cmc/zai-org/GLM-5.2", name: "GLM-5.2 (CMC)" },
    { id: "cp/cline-pass/deepseek-v4-flash", name: "DeepSeek V4 Flash (Cline Pass)" },
    { id: "cp/cline-pass/deepseek-v4-pro", name: "DeepSeek V4 Pro (Cline Pass)" },
    { id: "cp/cline-pass/glm-5.2", name: "GLM-5.2 (Cline Pass)" },
    { id: "cp/cline-pass/kimi-k2.6", name: "Kimi K2.6 (Cline Pass)" },
    { id: "cp/cline-pass/kimi-k2.7-code", name: "Kimi K2.7 Code (Cline Pass)" },
    { id: "cp/cline-pass/mimo-v2.5", name: "MiMo V2.5 (Cline Pass)" },
    { id: "cp/cline-pass/mimo-v2.5-pro", name: "MiMo V2.5 Pro (Cline Pass)" },
    { id: "cp/cline-pass/minimax-m3", name: "MiniMax M3 (Cline Pass)" },
    { id: "cp/cline-pass/qwen3.7-max", name: "Qwen3.7 Max (Cline Pass)" },
    { id: "cp/cline-pass/qwen3.7-plus", name: "Qwen3.7 Plus (Cline Pass)" },
    { id: "cx/gpt-5.4", name: "GPT-5.4 (CX)" },
    { id: "cx/gpt-5.4-mini", name: "GPT-5.4 Mini (CX)" },
    { id: "cx/gpt-5.5", name: "GPT-5.5 (CX)" },
    { id: "cx/gpt-5.6-terra", name: "GPT-5.6 Terra (CX)" },
    { id: "mimo/mimo-v2-flash", name: "MiMo V2 Flash" },
    { id: "mimo/mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "mimo/mimo-v2-pro", name: "MiMo V2 Pro" },
    { id: "mimo/mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo/mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "ocg/deepseek-v4-flash", name: "DeepSeek V4 Flash (OCG)" },
    { id: "ocg/deepseek-v4-pro", name: "DeepSeek V4 Pro (OCG)" },
    { id: "ocg/glm-5.1", name: "GLM-5.1 (OCG)" },
    { id: "ocg/kimi-k2.6", name: "Kimi K2.6 (OCG)" },
    { id: "ocg/kimi-k2.7-code", name: "Kimi K2.7 Code (OCG)" },
    { id: "ocg/mimo-v2.5", name: "MiMo V2.5 (OCG)" },
    { id: "ocg/mimo-v2.5-pro", name: "MiMo V2.5 Pro (OCG)" },
    { id: "ocg/minimax-m2.5", name: "MiniMax M2.5 (OCG)" },
    { id: "ocg/minimax-m2.7", name: "MiniMax M2.7 (OCG)" },
    { id: "ocg/minimax-m3", name: "MiniMax M3 (OCG)" },
    { id: "ocg/qwen3.6-plus", name: "Qwen3.6 Plus (OCG)" },
    { id: "ocg/qwen3.7-plus", name: "Qwen3.7 Plus (OCG)" },
    { id: "sf/MiniMaxAI/MiniMax-M3", name: "MiniMax M3 (SF)" },
    { id: "sf/deepseek-ai/DeepSeek-V4-Flash", name: "DeepSeek V4 Flash (SF)" },
    { id: "sf/deepseek-ai/DeepSeek-V4-Pro", name: "DeepSeek V4 Pro (SF)" },
    { id: "sf/meituan-longcat/LongCat-2.0", name: "LongCat 2.0 (SF)" },
    { id: "sf/moonshotai/Kimi-K2.5", name: "Kimi K2.5 (SF)" },
    { id: "sf/moonshotai/Kimi-K2.6", name: "Kimi K2.6 (SF)" },
    { id: "sf/moonshotai/Kimi-K2.7-Code", name: "Kimi K2.7 Code (SF)" },
    { id: "sf/zai-org/GLM-5", name: "GLM-5 (SF)" },
    { id: "sf/zai-org/GLM-5.1", name: "GLM-5.1 (SF)" },
    { id: "sf/zai-org/GLM-5.2", name: "GLM-5.2 (SF)" },
    { id: "zai/glm-4.6v", name: "GLM-4.6V (ZAI)" },
    { id: "zai/glm-4.7", name: "GLM-4.7 (ZAI)" },
    { id: "zai/glm-5", name: "GLM-5 (ZAI)" },
    { id: "zai/glm-5-turbo", name: "GLM-5 Turbo (ZAI)" },
    { id: "zai/glm-5.1", name: "GLM-5.1 (ZAI)" },
    { id: "zai/glm-5.2", name: "GLM-5.2 (ZAI)" },
    { id: "free/grok/grok-4.5", name: "Grok 4.5 (Free)" },
    { id: "free/kiro/MiniMax-M2.5", name: "MiniMax M2.5 (Free Kiro)" },
    { id: "free/kiro/claude-haiku-4.5", name: "Claude Haiku 4.5 (Free Kiro)" },
    { id: "free/kiro/claude-sonnet-4.5", name: "Claude Sonnet 4.5 (Free Kiro)" },
    { id: "free/kiro/glm-5", name: "GLM-5 (Free Kiro)" },
    { id: "free/sff/tencent/Hy3", name: "Hunyuan Hy3 (Free SFF)" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "glm-5", name: "GLM-5" },
    { id: "glm-5.1", name: "GLM-5.1" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "longcat-2.0", name: "LongCat 2.0" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "minimax-m3", name: "MiniMax M3" },
  ],
  serviceKinds: ["llm"],
  modelsFetcher: { url: "https://api.inferhub.dev/v1/models", type: "openai" },
  passthroughModels: true,
};
